version: '3.2'
services:
  nginx:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    ports:
      - "80:80"
    depends_on:
      - app
  app:
    restart: always
    environment:
      - ADM_PASSWORD=Blaa
      - ADM_USERNAME=Blaa
      - MAILUSERNAME=example@mail.no
      - MAILUSERPASSWORD=Pa$$w0rd
      - SMTP=smtp.example.no
      - DOMAIN=localhost
      - EMAILNOTIFICATION=true
      - PRODUCTID=true
      - WEBPORT=8087
      - VIRTUAL_HOST=docker.inity.no
    build: .
    ports:
      - 8087-8097:8087
    depends_on:
      - mongo  
    expose:
      - 8087
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    volumes:
#       - ./data:/data/db
#       - mongo_storage:/data
        - ~/data:/data/db
# docker volume create --name mongo_storage
volumes:
  mongo_storage:
    external: true